{% set name = "abi3info" %}
{% set version = "2023.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/abi3info-{{ version }}.tar.gz
  sha256: b7ca7f866eb6f46de6e76b78d173f14e4f5b0aafa93e5c1737cc29aab69a8dbd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - abi3info
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/abi3info/
  summary: A library for abi3 and other CPython API information
  dev_url: https://github.com/woodruffw/abi3info
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
